# -*- coding: utf-8 -*-
"""nat2-gas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11mP58BKuhc_sfAGJyFmomY7MXkazJBCe
"""

import pandas as pd
import numpy as np
from datetime import date, timedelta
import matplotlib.pyplot as plt

df = pd.read_csv('Nat_Gas.csv')
df.columns = ['date', 'price']
df['date'] = pd.to_datetime(df['date'])

prices = df['price'].values
dates = df['date'].values

start_date = df['date'].min().date()
end_date = df['date'].max().date()

months = []
year = start_date.year
month = start_date.month

while True:
    current = date(year, month, 1) + timedelta(days=-1)
    months.append(current)
    if current >= end_date:
        break
    month = (month % 12) + 1
    if month == 1:
        year += 1

days_from_start = np.array([(d - start_date).days for d in months])

def simple_regression(x, y):
    x_bar = np.mean(x)
    y_bar = np.mean(y)
    slope = np.sum((x - x_bar)*(y - y_bar)) / np.sum((x - x_bar)**2)
    intercept = y_bar - slope * x_bar
    return slope, intercept

# Calculate days from start date corresponding to the 'dates' in the DataFrame
days_from_df_dates = np.array([(pd.Timestamp(d).date() - start_date).days for d in dates])
slope, intercept = simple_regression(days_from_df_dates, prices)

residuals = prices - (slope * days_from_df_dates + intercept)

sin_t = np.sin(2 * np.pi * days_from_df_dates / 365)
cos_t = np.cos(2 * np.pi * days_from_df_dates / 365)

a = np.sum(residuals * sin_t) / np.sum(sin_t**2)
b = np.sum(residuals * cos_t) / np.sum(cos_t**2)

amplitude = np.sqrt(a**2 + b**2)
phase = np.arctan2(b, a)

def interpolate_price(input_date):
    input_date = pd.to_datetime(input_date)
    days = (input_date.date() - start_date).days
    return (
        slope * days
        + intercept
        + amplitude * np.sin(2 * np.pi * days / 365 + phase)
    )

def price_storage_contract(
    injection_dates,
    withdrawal_dates,
    injection_rate,
    withdrawal_rate,
    max_storage_volume,
    storage_cost_per_unit_per_day
):
    injection_dates = [pd.Timestamp(d) for d in injection_dates]
    withdrawal_dates = [pd.Timestamp(d) for d in withdrawal_dates]

    all_dates = sorted(injection_dates + withdrawal_dates)

    inventory = 0.0
    cashflow = 0.0
    inventory_over_time = {}

    for d in all_dates:
        # Inject
        if d in injection_dates:
            qty = min(injection_rate, max_storage_volume - inventory)
            inventory += qty
            cashflow -= qty * interpolate_price(d)

        # Withdraw
        if d in withdrawal_dates:
            qty = min(withdrawal_rate, inventory)
            inventory -= qty
            cashflow += qty * interpolate_price(d)

        inventory_over_time[d] = inventory

    # Storage costs
    inventory_series = pd.Series(inventory_over_time).sort_index()
    storage_cost = inventory_series.sum() * storage_cost_per_unit_per_day

    return {
        "Contract Value": cashflow - storage_cost,
        "Trading Cashflow": cashflow,
        "Storage Cost": storage_cost,
        "Final Inventory": inventory
    }

result = price_storage_contract(
    injection_dates=["2024-06-30", "2024-07-31"],
    withdrawal_dates=["2024-12-31", "2025-01-31"],
    injection_rate=500_000,
    withdrawal_rate=500_000,
    max_storage_volume=1_000_000,
    storage_cost_per_unit_per_day=0.0004
)

for k, v in result.items():
    print(f"{k}: {v:,.2f}")