# -*- coding: utf-8 -*-
"""Nat_gas_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A6iXjvEypfIdhu-JiulFgbPhM2qsVqUZ
"""

import pandas as pd

df_natural_gas_price = pd.read_csv('Nat_Gas.csv')

# Standardize column names
df_natural_gas_price.columns = ['date', 'price']

# Convert date column to datetime
df_natural_gas_price['date'] = pd.to_datetime(df_natural_gas_price['date'])

# Set date as index
df_natural_gas_price.set_index('date', inplace=True)

print(df_natural_gas_price.head())
print(df_natural_gas_price.info())

df_natural_gas_price['month'] = df_natural_gas_price.index.month
print(df_natural_gas_price[['month']].head())

monthly_avg_prices = (
    df_natural_gas_price
    .groupby('month')['price']
    .mean()
    .reset_index()
)

print(monthly_avg_prices)
print(monthly_avg_prices.columns)

print("Checking for missing values:")
print(df_natural_gas_price.isnull().sum())

print("\nDataFrame after verifying index. Displaying the first 5 rows:")
print(df_natural_gas_price.head())
print("\nChecking data types and index after verification:")
print(df_natural_gas_price.info())

import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style('whitegrid')

plt.figure(figsize=(12, 6))
plt.plot(df_natural_gas_price.index, df_natural_gas_price['price'], label='Natural Gas Price', color='skyblue')
plt.title('Historical Natural Gas Prices Over Time')
plt.xlabel('Date')
plt.ylabel('Price')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 6))
sns.barplot(
    x='month',
    y='price',
    data=monthly_avg_prices
)

plt.title('Average Natural Gas Prices by Month')
plt.xlabel('Month')
plt.ylabel('Average Price')
plt.xticks(
    ticks=range(12),
    labels=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']
)
plt.grid(axis='y', linestyle='--')
plt.tight_layout()
plt.show()

df_natural_gas_price['Month'] = df_natural_gas_price.index.month
monthly_avg_prices = df_natural_gas_price.groupby('Month')['price'].mean().reset_index()

plt.figure(figsize=(10, 6))
sns.barplot(x='Month', y='price', data=monthly_avg_prices, palette='viridis', hue='Month', legend=False)
plt.title('Average Natural Gas Prices by Month')
plt.xlabel('Month')
plt.ylabel('Average Price')
plt.xticks(ticks=range(0, 12), labels=['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])
plt.grid(axis='y', linestyle='--')
plt.tight_layout()
plt.show()

from statsmodels.tsa.seasonal import seasonal_decompose
from sklearn.linear_model import LinearRegression
import numpy as np

print("Required libraries imported: seasonal_decompose, LinearRegression, numpy")

decomposition = seasonal_decompose(df_natural_gas_price['price'], model='additive', period=12)

trend = decomposition.trend
seasonal = decomposition.seasonal

print("Seasonal decomposition performed. Trend and seasonal components extracted.")
print("First 5 values of trend component:\n", trend.head())
print("First 5 values of seasonal component:\n", seasonal.head())

df_trend = pd.DataFrame({'Trend': trend.dropna()})
df_trend['Time'] = np.arange(len(df_trend))

print("df_trend DataFrame created with 'Trend' and 'Time' columns:")
print(df_trend.head())
print(df_trend.tail())

trend_model = LinearRegression()
trend_model.fit(df_trend[['Time']], df_trend['Trend'])

print("Linear Regression model fitted to the trend component.")

last_historical_date = df_natural_gas_price.index.max()
future_dates = pd.date_range(start=last_historical_date + pd.DateOffset(months=1), periods=12, freq='MS')

print("Generated future dates for the next 12 months:")
print(future_dates)

last_time_index = df_trend['Time'].max()
future_time_indices = np.arange(last_time_index + 1, last_time_index + 1 + len(future_dates))
future_trend_prediction = trend_model.predict(future_time_indices.reshape(-1, 1))

print("Future time indices:")
print(future_time_indices)
print("Predicted future trend values:")
print(future_trend_prediction)

seasonal_pattern = seasonal.groupby(seasonal.index.month).mean()
avg_seasonal_pattern = pd.Series(seasonal_pattern, index=range(1, 13))

print("Average seasonal pattern for each month:")
print(avg_seasonal_pattern)

future_months = future_dates.month
future_seasonal_prediction = [avg_seasonal_pattern[month] for month in future_months]

extrapolated_prices = future_trend_prediction + np.array(future_seasonal_prediction)

print("Extrapolated prices (trend + seasonal component):")
print(extrapolated_prices)

df_extrapolated_prices = pd.DataFrame({
    'Prices': extrapolated_prices
}, index=future_dates)

print("DataFrame of extrapolated prices created. Displaying the first 5 rows:")
print(df_extrapolated_prices.head())
print("\nChecking data types and index of df_extrapolated_prices:")
print(df_extrapolated_prices.info())

combined_prices = pd.concat([df_natural_gas_price[['price']], df_extrapolated_prices])

def estimate_price(target_date):
    target_date = pd.to_datetime(target_date)

    if target_date in combined_prices.index:
        return combined_prices.loc[target_date, 'Prices']
    else:
        # Check if the target_date is between the earliest and latest dates in the combined data
        if target_date < combined_prices.index.min() or target_date > combined_prices.index.max():
            return f"Price cannot be estimated for {target_date.strftime('%Y-%m-%d')} as it is outside the available historical and extrapolated range."
        else:
            # This case implies a date exists within the range but isn't a direct match (e.g., daily data not available for monthly data)
            # For this monthly dataset,will only consider exact matches.
            return f"Price cannot be estimated for {target_date.strftime('%Y-%m-%d')} on a non-exact monthly date."


print("Price estimation function 'estimate_price' defined.")

print("Testing the estimate_price function:")

# Test with a historical date
historical_date = '2022-01-31'
print(f"Estimated price for {historical_date}: {estimate_price(historical_date)}")

# Test with an extrapolated date
extrapolated_date = '2025-05-01'
print(f"Estimated price for {extrapolated_date}: {estimate_price(extrapolated_date)}")

# Test with a date outside both ranges (before historical)
out_of_range_before = '2019-01-01'
print(f"Estimated price for {out_of_range_before}: {estimate_price(out_of_range_before)}")

# Test with a date outside both ranges (after extrapolated)
out_of_range_after = '2025-11-01'
print(f"Estimated price for {out_of_range_after}: {estimate_price(out_of_range_after)}")

# Test with a non-exact monthly date within range
non_exact_date_within_range = '2022-01-15'
print(f"Estimated price for {non_exact_date_within_range}: {estimate_price(non_exact_date_within_range)}")

plt.figure(figsize=(14, 7))
plt.plot(df_natural_gas_price.index, df_natural_gas_price['price'], label='Historical Prices', color='skyblue')
plt.plot(df_extrapolated_prices.index, df_extrapolated_prices['Prices'], label='Extrapolated Prices', color='orange', linestyle='--')

plt.title('Historical and Extrapolated Natural Gas Prices')
plt.xlabel('Date')
plt.ylabel('Price')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()