# -*- coding: utf-8 -*-
"""task3jp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YVhn1741ZYN0zUoEP3jXWogeQ13t_7cS
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score

# Load the provided dataset
df = pd.read_csv("Task 3 and 4_Loan_Data.csv")

print(df.head())
print(df.info())

TARGET = "default"

X = df.drop(columns=[TARGET])
y = df[TARGET]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.25,
    random_state=42,
    stratify=y
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

pd_model = LogisticRegression(max_iter=1000)
pd_model.fit(X_train_scaled, y_train)

pd_test = pd_model.predict_proba(X_test_scaled)[:, 1]
auc = roc_auc_score(y_test, pd_test)

print(f"Logistic Regression ROC-AUC: {auc:.3f}")

RECOVERY_RATE = 0.10
LGD = 1 - RECOVERY_RATE

def expected_loss(loan_features: dict) -> dict:
    """
    Takes loan & borrower features and returns:
    - Probability of Default (PD)
    - Expected Loss (EL)
    """

    X_new = pd.DataFrame([loan_features])

    # Exposure at Default (loan balance)
    exposure = X_new["loan_amt_outstanding"].iloc[0]

    # Scale inputs
    X_new_scaled = scaler.transform(X_new)

    # Predict PD
    pd_estimate = pd_model.predict_proba(X_new_scaled)[0, 1]

    # Expected Loss
    el = pd_estimate * LGD * exposure

    return {
        "Probability of Default": pd_estimate,
        "Expected Loss": el
    }

sample_loan = {
    "customer_id": 12345, # Placeholder ID
    "credit_lines_outstanding": 1, # Example value
    "loan_amt_outstanding": 12000, # Mapped from original 'loan_amt'
    "total_debt_outstanding": 23100, # Derived from original 'debt_to_income' (0.42 * 55000)
    "income": 55000,
    "years_employed": 5,
    "fico_score": 680 # Mapped from original 'credit_score'
}

result = expected_loss(sample_loan)

print(f"PD: {result['Probability of Default']:.2%}")
print(f"Expected Loss: ${result['Expected Loss']:,.2f}")

from sklearn.tree import DecisionTreeClassifier

tree_model = DecisionTreeClassifier(
    max_depth=4,
    min_samples_leaf=50,
    random_state=42
)

tree_model.fit(X_train, y_train)
tree_pd = tree_model.predict_proba(X_test)[:, 1]

tree_auc = roc_auc_score(y_test, tree_pd)
print(f"Decision Tree ROC-AUC: {tree_auc:.3f}")